### ISSUE TITLE
Integration with easyPyPI

### ISSUE THREAD

**Issue by PFython** [m-vdb/pep440-version-utils#2]
Hi Maxime!

First of all congratulations/thanks... I was looking for exactly this kind of utility and it seems like a really intuitive and helpful implementation 👍 

I've recently published a tool called [`easyPyPI` ](https://github.com/PFython/easypypi) to simplify package publishing to PyPI and currently only have a very basic `next_version()` function to upversion packages.

I think I can simply import pep440-version-utils into `easyPyPI` myself but wondered if you might be interested in joining me as a contributor and maybe integrate it yourself since pepr440-eversion-utils is your 'baby'?

All the best, and I hope to hear back from your soon!
Peter

**Comment by PFython** [comment]
Update - thanks to Covid Lockdown I found myself with some extra time today and have gone ahead and integrated the "next version" functions in `easyPyPI`.  Please have a look and let me know what you think!

All the best,
Peter

**Comment by m-vdb** [comment]
Hi @PFython, apologies for not seeing your issue earlier. Great to see that you've integrated this package into `easyPyPI` 💯  and thanks for the credit in your README :)
